language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm i
  - npm run build
  - cp dist/index.html dist/404.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main